# Apstra API Configuration
apstra:
  host: "10.28.173.3"
  username: "se_demo"
  password: "se_demo"
  blueprints:
    - id: "a7c2cd1d-da6e-4c3c-8e34-acbd131d3e76"
      name: "production-blueprint"
      enabled: true
    - id: "a7c2cd1d-da6e-4c3c-8e34-acbd131d3e24"
      name: "staging-blueprint"
      enabled: true
  poll_interval: 30
  api_timeout: 10
  token_refresh_buffer: 1200


redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  connection_pool_size: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  keys:
    task_state: "apstra:task:state:"
    task_history: "apstra:task:history:"
    message_queue: "apstra:queue:messages"
    retry_queue: "apstra:queue:retry"
    failed_queue: "apstra:queue:failed"
  ttl:
    task_history: 604800
    failed_messages: 259200

snmp:
  destinations:
    - host: "192.168.1.200"
      port: 162
      community: "public"
      version: "2c"
    - host: "192.168.1.201"
      port: 162
      community: "monitoring"
      version: "2c"
  oids:
    base_oid: "1.3.6.1.4.1.2636.1.1.1.1"
    alert_probe: "101"
    alert_hostname: "102"
    audit_event: "100"
    task_event: "200"

syslog:
  listen_port: 514
  listen_address: "0.0.0.0"
  buffer_size: 1024

application:
  log_level: "INFO"
  log_file: "./apstra_snmp_converter.log"
  max_retries: 3
  retry_delay: 5
  worker_processes: 2
  queue_batch_size: 10
